### ISSUE TITLE
Checkboxes for optional object properties with fixed values

### ISSUE THREAD

**Issue by brollb** [webgme/svelte-jsonschema-form#4]
If an object has optional properties, it should be able to be explicitly removed via a checkbox. I thought this was already in the main branch (as @romancow has demoed it) but I don't see it on the github pages version.

**Comment by romancow** [comment]
There was never a way to "explicitly" remove optional fields. Currently to not have an optional value, you just leave it empty/blank.

**Comment by brollb** [comment]
Oh, I was referring to the checkboxes on the accordions that you demoed a little while back. Has that been merged into the main branch?

**Comment by romancow** [comment]
Yes, that should be. But I haven't created a new "release" on github yet, which is what triggers the pages update. I can do that.
