### ISSUE TITLE
"ignoreEmpty" ui option

### ISSUE THREAD

**Issue by brollb** [webgme/svelte-jsonschema-form#7]
There are times when we want the dropdown accordion to just be a UI element and only be present in the output data if a child is selected. In these cases, it should not have a checkbox next to it and the key should only be added to the object if a child is selected.

This could be configured via `ignoreEmpty` and another option for disabling the checkbox or it could be a standalone setting that does both - maybe `accordion` or something.

**Comment by romancow** [comment]
@brollb Hey, I don't really remember the details of the "and another option for disabling the checkbox or it could be a standalone setting that does both - maybe accordion or something" part. Do you mind expounding on how this other option would work / the use case?

**Comment by brollb** [comment]
Sure. Consider a vocabulary accordion. We might want to expand it to view the terms and then decide not to select any and just download the tags that we have populated. In this case, we don't really want to have to close the vocabulary accordion nor do we really want to have a checkbox by the vocabulary since it doesn't make any sense to select a vocabulary without a term in the vocab.

Does that make sense?

**Comment by romancow** [comment]
How does that differ from the "ignoreEmpty" option? What would be the difference between how to two work?

**Comment by brollb** [comment]
Really just a UI difference (ie, hide the checkbox so it looks and feels more like a simple UI accordion).

**Comment by romancow** [comment]
Hmm, do we need the checkbox for the "ignoreEmpty" option? I guess the only situation where we do would be when an accordian with the "ignoreEmpty" option has default options? Checking it would add the default data. Whereas for this other option, it's like an "ignoreEmpty" where it's permanently selected. So if it has default values, they'd exist in the data already.

Does that sound right?
